FROM python:3.11-slim-bullseye

WORKDIR /usr/src

COPY update_dash.py ./
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt \ 
&& python update_dash.py \
&& rm update_dash.py

USER daemon