name: Docker Images

on:
  release:
    types: [created]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Publish container
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: dashpool/basecontainer
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        Dockerfile: Dockerfile.slim
        workdir: .
        tags: "${{ github.event.release.tag_name }}"

    - name: Publish container
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: dashpool/basecontainer
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        Dockerfile: Dockerfile.dev
        workdir: .
        tags: "${{ github.event.release.tag_name }}-dev"


    # - name: Create exampleapp release
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     TARGET_REPO_OWNER: dashpool
    #     TARGET_REPO_NAME: exampleapp
    #     TAG_NAME: ${{ github.event.release.tag_name }}
    #     TAG_DESCRIPTION: ${{ github.event.release.description }}
    #   run: |
    #     curl -X POST \
    #         -H "Accept: application/vnd.github.v3+json" \
    #         -H "Authorization: token $GITHUB_TOKEN" \
    #         -d '{"tag_name": "'"$TAG_NAME"'", "name": "Release '"$TAG_NAME"'", "body": "'"$TAG_DESCRIPTION"'"}' \
    #         "https://api.github.com/repos/$TARGET_REPO_OWNER/$TARGET_REPO_NAME/releases"

    # - name: Create frontend release
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     TARGET_REPO_OWNER: dashpool
    #     TARGET_REPO_NAME: frontend
    #     TAG_NAME: ${{ github.event.release.tag_name }}
    #     TAG_DESCRIPTION: ${{ github.event.release.description }}
    #   run: |
    #     curl -X POST \
    #         -H "Accept: application/vnd.github.v3+json" \
    #         -H "Authorization: token $GITHUB_TOKEN" \
    #         -d '{"tag_name": "'"$TAG_NAME"'", "name": "Release '"$TAG_NAME"'", "body": "'"$TAG_DESCRIPTION"'"}' \
    #         "https://api.github.com/repos/$TARGET_REPO_OWNER/$TARGET_REPO_NAME/releases"            


    # - name: Create backend release
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     TARGET_REPO_OWNER: dashpool
    #     TARGET_REPO_NAME: backend
    #     TAG_NAME: ${{ github.event.release.tag_name }}
    #     TAG_DESCRIPTION: ${{ github.event.release.description }}
    #   run: |
    #     curl -X POST \
    #         -H "Accept: application/vnd.github.v3+json" \
    #         -H "Authorization: token $GITHUB_TOKEN" \
    #         -d '{"tag_name": "'"$TAG_NAME"'", "name": "Release '"$TAG_NAME"'", "body": "'"$TAG_DESCRIPTION"'"}' \
    #         "https://api.github.com/repos/$TARGET_REPO_OWNER/$TARGET_REPO_NAME/releases"   


    # - name: Create admin release
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     TARGET_REPO_OWNER: dashpool
    #     TARGET_REPO_NAME: admin
    #     TAG_NAME: ${{ github.event.release.tag_name }}
    #     TAG_DESCRIPTION: ${{ github.event.release.description }}
    #   run: |
    #     curl -X POST \
    #         -H "Accept: application/vnd.github.v3+json" \
    #         -H "Authorization: token $GITHUB_TOKEN" \
    #         -d '{"tag_name": "'"$TAG_NAME"'", "name": "Release '"$TAG_NAME"'", "body": "'"$TAG_DESCRIPTION"'"}' \
    #         "https://api.github.com/repos/$TARGET_REPO_OWNER/$TARGET_REPO_NAME/releases"               